package com.blogspot.blogsetyaaji.kumpulanappbasic;

/**
 * Created by DELL on 22/07/2017.
 */

public class DeskripsiHewan {
    String[] deskripsi = {
            "Ayam peliharaan (Gallus gallus domesticus) adalah unggas yang biasa dipelihara orang untuk dimanfaatkan untuk keperluan hidup pemeliharanya. Ayam peliharaan (selanjutnya disingkat \"ayam\" saja) merupakan keturunan langsung dari salah satu subspesies ayam hutan yang dikenal sebagai ayam hutan merah (Gallus gallus) atau ayam bangkiwa (bankiva fowl). Kawin silang antarras ayam telah menghasilkan ratusan galur unggul atau galur murni dengan bermacam-macam fungsi; yang paling umum adalah ayam potong (untuk dipotong) dan ayam petelur (untuk diambil telurnya). Ayam biasa dapat pula dikawin silang dengan kerabat dekatnya, ayam hutan hijau, yang menghasilkan hibrida mandul yang jantannya dikenal sebagai ayam bekisar.\n" +
                    "Dengan populasi lebih dari 24 milyar pada tahun 2003, Firefly's Bird Encyclopaedia menyatakan ada lebih banyak ayam di dunia ini daripada burung lainnya. Ayam memasok dua sumber protein dalam pangan: daging ayam dan telur.\n" +
                    "Sudut pandang tradisional peternakan ayam dalam domestikasi spesies ini termaktub dalam Encyclopædia Britannica (2007): \"Manusia pertama mendomestikasi ayam asal India untuk keperluan adu ayam di Asia, Afrika, dan Eropa. Tidak ada perhatian khusus diberikan ke produksi telur atau daging ... \""
            , "Ayam peliharaan (Gallus gallus domesticus) adalah unggas yang biasa dipelihara orang untuk dimanfaatkan untuk keperluan hidup pemeliharanya. Ayam peliharaan (selanjutnya disingkat \"ayam\" saja) merupakan keturunan langsung dari salah satu subspesies ayam hutan yang dikenal sebagai ayam hutan merah (Gallus gallus) atau ayam bangkiwa (bankiva fowl). Kawin silang antarras ayam telah menghasilkan ratusan galur unggul atau galur murni dengan bermacam-macam fungsi; yang paling umum adalah ayam potong (untuk dipotong) dan ayam petelur (untuk diambil telurnya). Ayam biasa dapat pula dikawin silang dengan kerabat dekatnya, ayam hutan hijau, yang menghasilkan hibrida mandul yang jantannya dikenal sebagai ayam bekisar.\n" +
            "Dengan populasi lebih dari 24 milyar pada tahun 2003, Firefly's Bird Encyclopaedia menyatakan ada lebih banyak ayam di dunia ini daripada burung lainnya. Ayam memasok dua sumber protein dalam pangan: daging ayam dan telur.\n" +
            "Sudut pandang tradisional peternakan ayam dalam domestikasi spesies ini termaktub dalam Encyclopædia Britannica (2007): \"Manusia pertama mendomestikasi ayam asal India untuk keperluan adu ayam di Asia, Afrika, dan Eropa. Tidak ada perhatian khusus diberikan ke produksi telur atau daging ... \""
            , "Ayam peliharaan (Gallus gallus domesticus) adalah unggas yang biasa dipelihara orang untuk dimanfaatkan untuk keperluan hidup pemeliharanya. Ayam peliharaan (selanjutnya disingkat \"ayam\" saja) merupakan keturunan langsung dari salah satu subspesies ayam hutan yang dikenal sebagai ayam hutan merah (Gallus gallus) atau ayam bangkiwa (bankiva fowl). Kawin silang antarras ayam telah menghasilkan ratusan galur unggul atau galur murni dengan bermacam-macam fungsi; yang paling umum adalah ayam potong (untuk dipotong) dan ayam petelur (untuk diambil telurnya). Ayam biasa dapat pula dikawin silang dengan kerabat dekatnya, ayam hutan hijau, yang menghasilkan hibrida mandul yang jantannya dikenal sebagai ayam bekisar.\n" +
            "Dengan populasi lebih dari 24 milyar pada tahun 2003, Firefly's Bird Encyclopaedia menyatakan ada lebih banyak ayam di dunia ini daripada burung lainnya. Ayam memasok dua sumber protein dalam pangan: daging ayam dan telur.\n" +
            "Sudut pandang tradisional peternakan ayam dalam domestikasi spesies ini termaktub dalam Encyclopædia Britannica (2007): \"Manusia pertama mendomestikasi ayam asal India untuk keperluan adu ayam di Asia, Afrika, dan Eropa. Tidak ada perhatian khusus diberikan ke produksi telur atau daging ... \""
            , "Ayam peliharaan (Gallus gallus domesticus) adalah unggas yang biasa dipelihara orang untuk dimanfaatkan untuk keperluan hidup pemeliharanya. Ayam peliharaan (selanjutnya disingkat \"ayam\" saja) merupakan keturunan langsung dari salah satu subspesies ayam hutan yang dikenal sebagai ayam hutan merah (Gallus gallus) atau ayam bangkiwa (bankiva fowl). Kawin silang antarras ayam telah menghasilkan ratusan galur unggul atau galur murni dengan bermacam-macam fungsi; yang paling umum adalah ayam potong (untuk dipotong) dan ayam petelur (untuk diambil telurnya). Ayam biasa dapat pula dikawin silang dengan kerabat dekatnya, ayam hutan hijau, yang menghasilkan hibrida mandul yang jantannya dikenal sebagai ayam bekisar.\n" +
            "Dengan populasi lebih dari 24 milyar pada tahun 2003, Firefly's Bird Encyclopaedia menyatakan ada lebih banyak ayam di dunia ini daripada burung lainnya. Ayam memasok dua sumber protein dalam pangan: daging ayam dan telur.\n" +
            "Sudut pandang tradisional peternakan ayam dalam domestikasi spesies ini termaktub dalam Encyclopædia Britannica (2007): \"Manusia pertama mendomestikasi ayam asal India untuk keperluan adu ayam di Asia, Afrika, dan Eropa. Tidak ada perhatian khusus diberikan ke produksi telur atau daging ... \""
            , "Ayam peliharaan (Gallus gallus domesticus) adalah unggas yang biasa dipelihara orang untuk dimanfaatkan untuk keperluan hidup pemeliharanya. Ayam peliharaan (selanjutnya disingkat \"ayam\" saja) merupakan keturunan langsung dari salah satu subspesies ayam hutan yang dikenal sebagai ayam hutan merah (Gallus gallus) atau ayam bangkiwa (bankiva fowl). Kawin silang antarras ayam telah menghasilkan ratusan galur unggul atau galur murni dengan bermacam-macam fungsi; yang paling umum adalah ayam potong (untuk dipotong) dan ayam petelur (untuk diambil telurnya). Ayam biasa dapat pula dikawin silang dengan kerabat dekatnya, ayam hutan hijau, yang menghasilkan hibrida mandul yang jantannya dikenal sebagai ayam bekisar.\n" +
            "Dengan populasi lebih dari 24 milyar pada tahun 2003, Firefly's Bird Encyclopaedia menyatakan ada lebih banyak ayam di dunia ini daripada burung lainnya. Ayam memasok dua sumber protein dalam pangan: daging ayam dan telur.\n" +
            "Sudut pandang tradisional peternakan ayam dalam domestikasi spesies ini termaktub dalam Encyclopædia Britannica (2007): \"Manusia pertama mendomestikasi ayam asal India untuk keperluan adu ayam di Asia, Afrika, dan Eropa. Tidak ada perhatian khusus diberikan ke produksi telur atau daging ... \""
    };
}
